MVC.Web/Controllers/AdminController.cs
using MVC.Domain.Model;
using MVC.Services;
using MVC.Services.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Repository;
using System.Data;

namespace MVC.Web.Controllers
{
    public class AdminController : Controller
    {
        private AccountService accountService = new AccountService();
        private DepartmentRepository departmentRepository = new DepartmentRepository();
        private DesignationRepository designationRepository = new DesignationRepository();
        private EmployeeRepository employeeRepository = new EmployeeRepository();
        private ChaRegisterService chaService = new ChaRegisterService();
        private VisitorRepository visitorRepository = new VisitorRepository();

        private ChaPassRepository chaPassRepository = new ChaPassRepository();

        private AccountRepository accountRepository = new AccountRepository();

      
        private string _userId; private string _roleId; private string _username;

        public string userId
        {
            get { return Request.Cookies["UserID"] != null ? Request.Cookies["UserID"].Value : ""; }
            set { _userId = Request.Cookies["UserID"] != null ? Request.Cookies["UserID"].Value : ""; }
        }

        public string roleId
        {
            get { return Request.Cookies["UserRoleID"] != null ? Request.Cookies["UserRoleID"].Value : ""; }
            set { _roleId = Request.Cookies["UserRoleID"] != null ? Request.Cookies["UserRoleID"].Value : ""; }
        }
        public string username
        {
            get { return Request.Cookies["UserName"] != null ? Request.Cookies["UserName"].Value : ""; }
            set { _username = Request.Cookies["UserName"] != null ? Request.Cookies["UserName"].Value : ""; }
        }
        public ActionResult Dashboard()
        {
            int roleid = Convert.ToInt32(roleId);
            int userid = Convert.ToInt32(userId);

            List<VisitorModel> visitors = visitorRepository.FetchAllVisitor(roleid, userid);
            ViewBag.VisitorCount = visitors.Count;

            DataTable UserDetail = visitorRepository.GetUserDetails(Convert.ToInt32(userId), Convert.ToInt32(roleId));

            ViewBag.FullName = UserDetail.Rows[0][0].ToString();
      

            DataTable AllCounts = visitorRepository.GetCountForDashboard();

            ViewBag.ChaRegister = AllCounts.Rows[0][1].ToString();
            ViewBag.Employee = AllCounts.Rows[1][1].ToString();
            ViewBag.Visitor = AllCounts.Rows[2][1].ToString();
            ViewBag.roleid = roleid;
            return View(visitors);  
        }

        public ActionResult Department()
        {
            List<DepartmentModel> department = departmentRepository.FetchDepartmentType();
            return View(department);
        }
        public ActionResult ChaMonthPass()
        {
            int roleid = Convert.ToInt32(roleId);
            int userid = Convert.ToInt32(userId);
            List<MonthlyPass> monthlyPasses = chaPassRepository.FetchChaMonthPassList(roleid, userid);
            return View(monthlyPasses);
        }
       

        public ActionResult AddDepartment()
        {
            return View();
        }

        public ActionResult Designation()
        {
            List<DesignationModel> designations = designationRepository.FetchDesignationType();
            return View(designations);
        }


        public ActionResult Employee()
        {
            List<EmployeeModel> employee = employeeRepository.FetchEmployeeType();

            List<SelectListModel> department = visitorRepository.GetDepartment();
            ViewBag.department = new SelectList(department, "ID", "Name");

            List<SelectListModel> designation = employeeRepository.GetDesignation();
            ViewBag.designation = new SelectList(designation, "ID", "Name");
            return View(employee);
        }

        public ActionResult AddDesignation()
        {
            return View();
        }

       

        public ActionResult AddEmployee()
        {

            List<SelectListModel> department = visitorRepository.GetDepartment();
            ViewBag.department = new SelectList(department, "ID", "Name");

            //List<SelectListModel> designation = visitorRepoitory.GetDesignation();
            //ViewBag.designation = new SelectList(designation, "ID", "Name");

            return View();
        }

        public ActionResult ViewEmployee()
        {
            return View();
        }

        public ActionResult Visitor()
        {
           

            List<SelectListModel> department = visitorRepository.GetDepartment();
            ViewBag.department = new SelectList(department, "ID", "Name");

            List<SelectListModel> officer = visitorRepository.GetOfficer();
            ViewBag.officer = new SelectList(officer, "ID", "Name");

            List<SelectListModel> visitorType = visitorRepository.GetVisitor();
            ViewBag.visitorType = new SelectList(visitorType, "ID", "Name");

            List<SelectListModel> documentType = visitorRepository.GetDocument();
            ViewBag.documentType = new SelectList(documentType, "ID", "Name");

            int roleid =Convert.ToInt32(roleId);
            int userid = Convert.ToInt32(userId);
            ViewBag.roleid = roleid;
            List<VisitorModel> visitors = visitorRepository.FetchAllVisitor(roleid, userid);



            return View(visitors);
        }

        public ActionResult AddVisitor()
        {
            List<SelectListModel> department = visitorRepository.GetDepartment();
            ViewBag.department = new SelectList(department, "ID", "Name");

            List<SelectListModel> officer = visitorRepository.GetOfficer();
            ViewBag.officer = new SelectList(officer, "ID", "Name");

            List<SelectListModel> visitorType = visitorRepository.GetVisitor();
            ViewBag.visitorType = new SelectList(visitorType, "ID", "Name");

            List<SelectListModel> documentType = visitorRepository.GetDocument();
            ViewBag.documentType = new SelectList(documentType, "ID", "Name");


            return View();
        }

        public ActionResult ViewVisitor()
        {
            return View();
        }

        public ActionResult PreRegistor()
        {
            return View();
        }

        public ActionResult AddPreRegistor()
        {
            return View();
        }

        public ActionResult ViewPreRegistor()
        {
            return View();
        }



        public ActionResult Cha()
        {
            ChaRegisterService chaService = new ChaRegisterService();
            List<ChaRegisterEntity> allcha = chaService.GetChaSummaryList();
            //return View(allUnits);
            return View(allcha);
        }



        public JsonResult CHaReject(int ID)
        {
            ChaRegisterService chaService = new ChaRegisterService();
            int userid = Convert.ToInt32(userId);
            DataTable result = chaService.Rejectcha(ID, userid);
            string message = "SUCCESS";
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CHaAccept(int ID)
        {
            ChaRegisterService chaService = new ChaRegisterService();
            int userid =Convert.ToInt32(userId);
            DataTable result = chaService.Acceptcha(ID, userid);
            string message = "SUCCESS";
            return Json(message, JsonRequestBehavior.AllowGet);
        }



        public JsonResult GetCHaAnalysisDetails(int ID)
        {

            ChaRegisterEntity result = chaService.getChadetail(ID);

            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;

        }


        public JsonResult VisitorCheckOutByID(string TokenNo)
        {
            DataTable result = accountRepository.CheckInVisitorByTokenNo(TokenNo);
            string msg = result.Rows[0][0].ToString();
            if (msg != "")
            {
                string message = "SUCCESS";
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            else
            {

                string message = "FAILED";
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            
        }

        public ActionResult UserDetail()
        {
            int RoleID = Convert.ToInt32(roleId);
            int UserID = Convert.ToInt32(userId);
            DataTable UserData = accountService.GetUserData(UserID, RoleID);
            ViewBag.UserName = UserData.Rows[0][2];
            ViewBag.UserEmail = UserData.Rows[0][1];
            return PartialView("_UserDetail");


            //return PartialView("SideMenu", MenuList);
        }

        public ActionResult LogOut()
        {
            
            Session.Abandon();

            return RedirectToAction("Login", "Account");
        }

    }
}

MVC.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Domain.Model;
using MVC.Repository;
using System.Data;
using System.IO;
using MVC.Services;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace MVC.Web.Controllers
{
    public class ReportController : Controller
    {
        private VisitorRepository visitorRepository = new VisitorRepository();
        // GET: Employee
        private string _userId; private string _roleId; private string _username;

        public string userId
        {
            get { return Request.Cookies["UserID"] != null ? Request.Cookies["UserID"].Value : ""; }
            set { _userId = Request.Cookies["UserID"] != null ? Request.Cookies["UserID"].Value : ""; }
        }

        public string roleId
        {
            get { return Request.Cookies["UserRoleID"] != null ? Request.Cookies["UserRoleID"].Value : ""; }
            set { _roleId = Request.Cookies["UserRoleID"] != null ? Request.Cookies["UserRoleID"].Value : ""; }
        }
        public string username
        {
            get { return Request.Cookies["UserName"] != null ? Request.Cookies["UserName"].Value : ""; }
            set { _username = Request.Cookies["UserName"] != null ? Request.Cookies["UserName"].Value : ""; }
        }

        public ActionResult VisitorReport()
        {
            int roleID = Convert.ToInt32(roleId);
            int userID = Convert.ToInt32(userId);
            DateTime StartDate = new DateTime(DateTime.Now.Year, 11, 1);
            DateTime EndDate = DateTime.Now;
            List<VisitorModel> VisitorReportlst = visitorRepository.GetVisitorReportDetailsLists(StartDate, EndDate, roleID, userID);
            return View(VisitorReportlst);
        }


        public PartialViewResult PreRegistorReport()
        {


            return PartialView("Myview");
        }
        public ActionResult AttendanceReport()
        {
            return View();
        }

        public ActionResult Visitor()
        {
           
            return View();
        }

        public PartialViewResult GetVisitorReportDetailsList(DateTime StartDate, DateTime EndDate)
        {
            int roleID = Convert.ToInt32(roleId);
            int userID = Convert.ToInt32(userId);
           VisitorModel VisitorReportlst = visitorRepository.GetVisitorReportDetailsList(StartDate, EndDate, roleID, userID);

            DataTable dt = visitorRepository.GetvisitorReportDetail(StartDate, EndDate, roleID, userID);
            Session["VisitorSummary"] = dt;
            return PartialView("_VisitorReport", VisitorReportlst);
            
        }
 

        public ActionResult ExportToExcelVisitors()
        {
            DataTable CompanyMaster = new DataTable();


            var CompanyName = "VMS";
            var CompanyAddress = "";
            DataTable getMovementICDNew = (DataTable)Session["VisitorSummary"];


            GridView gridview = new GridView();
            gridview.DataSource = getMovementICDNew;


            gridview.DataBind();

            Response.Clear();
            Response.Buffer = true;
            Response.Charset = "";
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment;filename=VisitorsReport.xls");
            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter htw = new HtmlTextWriter(sw))

                {

                    // render the GridView to the HtmlTextWriter
                    htw.Write("<table><tr><td  style='font-weight: bold; text-align: center'; colspan ='7'><strong style='font-size: 26px'>" + CompanyName + " <strong></td></tr>");
                    htw.Write("<table><tr><td  style='font-weight: bold; text-align: center'; colspan ='7'><strong style='font-size: 15px'>" + CompanyAddress + " <strong></td></tr>");
                    htw.Write("<table><tr><td  style='font-weight: bold; text-align: center'; colspan ='7'><strong style='font-size: 15px'>Complain Report<strong></td></tr>");

                    // htw.Write("<table><tr><td colspan='7'><h6 style='text-align:left'>  </h6></td></tr>");
                    gridview.RenderControl(htw);
                    // Output the GridView content saved into StringWriter
                    Response.Output.Write(sw.ToString());
                    Response.Flush();
                    Response.End();
                }
            }

            return View();
        }

    }
}

MVC.Web/Views/Report/AttendanceReport.cshtml
@{
    ViewBag.Title = "Attendance Report";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<section class="section">
    <div class="section-header">
        <h1>Attendance Report</h1>
        <ol class="breadcrumb">

            <li class="breadcrumb-item"><a href=@Url.Action("Dashboard", "Admin")>Dashboard</a></li>


            <li class="breadcrumb-item active">Attendance</li>

        </ol>


    </div>

    <div class="section-body">
        <div class="card">
            <div class="card-body">
                <form action="https://demo.quickpass.xyz/admin/attendance-report" method="POST">
                    <input type="hidden" name="_token" value="zqHFaOzgpwZQldiJZePT2wudDxeGvii0FyUUoi4P">                        <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>From Date</label>
                                <input type="text" name="from_date" class="form-control  datepicker" value="01-10-2023">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>To Date</label>
                                <input type="text" name="to_date" class="form-control  datepicker" value="25-10-2023">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <label for="">&nbsp;</label>
                            <button class="btn btn-primary form-control" type="submit">Get Report</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h5>Attendance Report</h5>
                <button class="btn btn-success btn-sm report-print-button" onclick="printDiv('printablediv')">Print</button>
            </div>
            <div class="card-body" id="printablediv">
                <h4 class="text-danger">The Attendance data not found</h4>
            </div>
        </div>
    </div>
</section>

MVC.Web/Views/Report/Myview.cshtml
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Partial View Title</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="myModalBody">
                <!-- Partial view content will be displayed here -->




            </div>
        </div>
    </div>
</div>
<script>
    alert('Hogya');
</script>

MVC.Web/Views/Report/PreRegistorReport.cshtml
@{
    ViewBag.Title = "Pre Registor Report";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="section-header">
    <h1>Pre-Registers Report</h1>
    <ol class="breadcrumb">

        <li class="breadcrumb-item"><a href=@Url.Action("Dashboard", "Admin")>Dashboard</a></li>


        <li class="breadcrumb-item active">Pre-registers</li>

    </ol>


</div>

<div class="section-body">
    <div class="card">
        <div class="card-body">
            <form action="https://demo.quickpass.xyz/admin/admin-pre-registers-report" method="POST">
                <input type="hidden" name="_token" value="zqHFaOzgpwZQldiJZePT2wudDxeGvii0FyUUoi4P">                        <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>From Date</label>
                            <input type="text" name="from_date" class="form-control  datepicker" value="01-10-2023">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>To Date</label>
                            <input type="text" name="to_date" class="form-control  datepicker" value="24-10-2023">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <label for="">&nbsp;</label>
                        <button class="btn btn-primary form-control" type="submit">Get Report</button>
                    </div>
                </div>
            </form>

        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h5>Pre-Registers Report</h5>
            <button class="btn btn-success btn-sm report-print-button" onclick="printDiv('printablediv')">Print</button>
        </div>
        <div class="card-body" id="printablediv">
            <h4 class="text-danger">The Pre-Registers data not found</h4>
        </div>
    </div>
</div>

MVC.Web/Views/Report/Visitor.cshtml
@{
    ViewBag.Title = "Visitor";
    if (ViewBag.roleid == 2)
    {
        Layout = "~/Views/Shared/_UserLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
}

<div id="visitorList">
    <div class="section-header">
        <h1>Visitor Report</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href=@Url.Action("Dashboard", "Admin")>Dashboard</a></li>
            <li class="breadcrumb-item active">Visitors</li>
        </ol>
    </div>

    <div class="section-body">
        <div class="card">
            <div class="card-body">
                <form action="" method="POST">
                    <input type="hidden" name="_token" value="zqHFaOzgpwZQldiJZePT2wudDxeGvii0FyUUoi4P">                        <div class="row">
                        <div class="col-lg-4 col-sm-4">
                            <div class="form-group">
                                <label>From Date</label>
                                <input type="date" name="from_date" id="val_start_date" class="form-control  datepicker">
                            </div>
                        </div>
                        <div class="col-lg-4 col-sm-4">
                            <div class="form-group">
                                <label>To Date</label>
                                <input type="date" name="to_date" id="val_to_date" class="form-control  datepicker">
                            </div>
                        </div>
                        <div class="col-lg-1" style="margin-top: 30px;">
                            <button class="btn btn-primary" onclick="FetchVisitorReportDetails()"><i class="fa fa-search"></i></button>
                        </div>
                        <div class="col-lg-2" style="margin-top: 30px;">

                            <button class="btn btn-success" name="btnExport" onclick="downloadExcelTemplate()">Export to Excel</button>
                        </div>

                    </div>
                </form>

            </div>

        </div>

    </div>
</div>



<input id="visitorID" type="hidden" value="0" />
<div id="viewVisitors"></div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>   
    function FetchVisitorReportDetails() {
    debugger
    var Start = $("#val_start_date").val();
    var End = $("#val_to_date").val();

    var requestData = {
        StartDate: Start,
        EndDate: End
    };

    $.ajax({
        url: "/Report/GetVisitorReportDetailsList",
        data: JSON.stringify(requestData),
        type: "POST",
        contentType: "application/json; charset=utf-8",
        success: function (data) {
    debugger
            $("#viewVisitors").html(data);
        },
        error: function (errormessage) {
            alert(errormessage.responseText);
        }
    });
}

</script>

MVC.Web/Views/Report/VisitorReport.cshtml
@{
    ViewBag.Title = "Visitor Report";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model List<MVC.Domain.Model.VisitorModel>
<div class="section-header">
    <h1>Visitor Report</h1>
    <ol class="breadcrumb">

        <li class="breadcrumb-item"><a href=@Url.Action("Dashboard", "Admin")>Dashboard</a></li>


        <li class="breadcrumb-item active">Visitors</li>

    </ol>


</div>

<div class="section-body">
    <div class="card">
        <div class="card-body">
            <input type="hidden" name="_token" value="zqHFaOzgpwZQldiJZePT2wudDxeGvii0FyUUoi4P">                        <div class="row">
                <div class="col-lg-4 col-sm-4">
                    <div class="form-group">
                        <label>From Date</label>
                        <input type="date" name="from_date" id="val_start_date" class="form-control  datepicker">
                    </div>
                </div>
                <div class="col-lg-4 col-sm-4">
                    <div class="form-group">
                        <label>To Date</label>
                        <input type="date" name="to_date" id="val_to_date" class="form-control  datepicker">
                    </div>
                </div>
                <div class="col-lg-1" style="margin-top: 30px;">
                    <button class="btn btn-primary" onclick="FetchVisitorReportDetails()"><i class="fa fa-search"></i></button>
                </div>
                <div class="col-lg-2" style="margin-top: 30px;">

                    <button class="btn btn-success" name="btnExport" onclick="downloadExcelTemplate()">Export to Excel</button>
                </div> 
            <div class="col-lg-2" style="margin-top: 30px;">

                    <button class="btn btn-success" name="btnExport" onclick="MyViewFunction()">Click Me</button>
                </div>

            </div>

            <div id="all_purchase_report" style="display:none;">
                <div class="table-responsive">
                    <table id="example" class="table table-striped dataTable no-footer">
                        <thead>
                            <tr>
                                @*
                            <th>SrNo</th>*@
                                <th>ID</th>
                                <th>TokenNo</th>
                                <th>InDateTime</th>
                                <th>OutDateTime</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {

                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.ID</td>
                                        <td>@item.TokenNo</td>
                                        <td>@item.InDateTime</td>
                                        <td>@item.OutDateTime</td>

                                    </tr>
                                }
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>

    </div>

</div>

<!-- Include your JavaScript libraries -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    function toggleTableVisibility() {
    debugger
         var tableDiv = document.getElementById("all_purchase_report");
        tableDiv.style.display = "block";
    }
</script>

<script>
    function tableShow(){
    $("#all_purchase_report").show();
    }

 function FetchVisitorReportDetails() {
    debugger;
    tableShow();
    var Start = $("#val_start_date").val();
    var End = $("#val_to_date").val();

    var element = {};
    element.StartDate = Start;
    element.EndDate = End;

    data = JSON.stringify(element);

    $.ajax({
        url: "/Report/GetVisitorReportDetailsList",
        type: "POST",
        data: data,
        contentType: "application/json; charset=utf-8",
        success: function (data) {
            debugger;

            // Update the partial view with the received data
            $('#all_purchase_report').html(data);
        }
    });
}

function downloadExcelTemplate() {
    debugger
    window.location = '@Url.Action("ExportToExcelVisitors", "Report")';
}



   function MyViewFunction() {

   
        
            $.ajax({
                url: "/Visitor/GetVisitorDetailByID",
                   
                type: "POST",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                  
                    $("#viewVisitors").html(data);

      document.getElementById('viewVisitors').style.display = 'block';
       document.getElementById('visitorList').style.display = 'none';
                   
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                  //  $("#tracker-loader").fadeOut("slow");
                }
            });

        }


</script>

MVC.Web/Views/Report/_VisitorReport.cshtml
@model List<MVC.Domain.Model.VisitorModel>
@{
    //ViewBag.Title = "Purchase Detail";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="table-responsive">
    <table id="example" class="table table-striped dataTable no-footer">
        <thead>
            <tr>
                @*
                    <th>SrNo</th>*@
                <th>ID</th>
                <th>TokenNo</th>
                <th>InDateTime</th>
                <th>OutDateTime</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {

                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ID</td>
                        <td>@item.TokenNo</td>
                        <td>@item.InDateTime</td>
                        <td>@item.OutDateTime</td>

                    </tr>
                }
            }
        </tbody>

    </table>
</div>