MVC.Web/Controllers/CheckInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Domain.Model;
using MVC.Repository;
using System.Data;
using QRCoder;
using System.Drawing;
using System.IO;


namespace MVC.Web.Controllers
{
    public class CheckInController : Controller
    {

        VisitorRepository visitorRepository = new VisitorRepository();

        public ActionResult StepTwo()
        {
            return View();
        }
        public ActionResult ShowCheckIn(string token)
        {
            VisitorModel model = visitorRepository.FetchVisitorByTokenNO(token);
            ViewBag.VisitorName = model.FirstName + " " + model.LastName;
            ViewBag.Phone = model.Phone;

            ViewBag.Officer = model.OfficerName;
            ViewBag.VisitorPic = model.VisitorPic;
            ViewBag.Email = model.Email;
            

            string SignedQRcode = "";

            SignedQRcode = token;

            if (SignedQRcode != "")
            {
                QRCodeGenerator qrGenerator = new QRCodeGenerator();

                QRCodeData qrCodeData = qrGenerator.CreateQrCode(SignedQRcode, QRCodeGenerator.ECCLevel.Q);

                QRCode qrCode = new QRCode(qrCodeData);

                // I am getting error in above line, or I am using below line of code but getting error. Unable to access QRCode withQRCodeGenerator.

                //QRCodeGenerator.QRCode qrCode = qrGenerator.CreateQrCode(ViewBag.SignedQRcode, QRCodeGenerator.ECCLevel.Q);

                using (Bitmap bitMap = qrCode.GetGraphic(20))
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        bitMap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                        byte[] byteImage = ms.ToArray();
                        ViewBag.path = "data:image/png;base64," + Convert.ToBase64String(byteImage);
                    }
                }
            }


            return View();
        }
        public ActionResult ScanQr()
        {
            //VisitorModel viewvisitorpassdetail = new  VisitorModel();
            //ViewBag.VisitorName = viewvisitorpassdetail.FirstName + " " + viewvisitorpassdetail.LastName;
            //ViewBag.Token = viewvisitorpassdetail.TokenNo;
            //ViewBag.Officer = viewvisitorpassdetail.OfficerName;
            //ViewBag.Department = viewvisitorpassdetail.DepartmentName;
            return View();
        }
        public ActionResult ViewVisitor(string token)
        {
            VisitorModel model = visitorRepository.FetchVisitorByTokenNO(token);
            ViewBag.VisitorName = model.FirstName + " " + model.LastName;
            ViewBag.Phone = model.Phone;
            ViewBag.VisitorPic = model.VisitorPic;
            ViewBag.Officer = model.OfficerName;
     
            ViewBag.Email = model.Email;

            return View();
        }
        public JsonResult ValidateVisitor(string Token)
        {
            ValidateVisitor response = new ValidateVisitor();
            int ID = visitorRepository.ValidateVisitor(Token);

            if (ID > 0)
 
            {
                string message = "SUCCESS";
                response.Message = message;
                response.VisitorID = ID;
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            else
            {

                string message = "FAILED";
                response.Message = message;
                response.VisitorID = ID;
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult AddVisitorCheckIn(string Token)
        {
            {

                DataTable result = visitorRepository.CheckInVisitorByTokenNo(Token);
                if (result != null)
                {
                    string message = "SUCCESS";
                    return Json(message, JsonRequestBehavior.AllowGet);
                }
                else
                {

                    string message = "FAILED";
                    return Json(message, JsonRequestBehavior.AllowGet);
                }


            }


        }

        public JsonResult VisitorLogEntry(string Token)
        {
            ValidateVisitor response = new ValidateVisitor();
            DataTable result = visitorRepository.CheckInVisitorByTokenNo(Token);
            if (result != null)
            {
                string message = "SUCCESS";
                response.Message = message;
               
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            else
            {

                string message = "SUCCESS";
                response.Message = message;
               
                return Json(message, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult ViewVisitorPassDetails(string token)
        {
            string TokenNo = Convert.ToString(token);
            VisitorModel viewvisitorpassdetail = visitorRepository.ViewVisitorPassDetails(TokenNo);

            var jsonResult = Json(viewvisitorpassdetail, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

    }
}

MVC.Web/Views/CheckIn/ScanQr.cshtml
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_FrontendLayout.cshtml";
}

<style>
    .Scanned_Details {
        border: none;
        background: none !important;
        padding-top: calc(0.375rem + 1px);
        padding-bottom: calc(0.375rem + 1px);
        margin-bottom: 0;
        font-size: inherit;
        line-height: 1;
        color: black !important;
    }

    .Scanned_Lable {
        padding-top: calc(0.375rem + 1px);
        padding-bottom: calc(0.375rem + 1px);
        margin-bottom: 0;
        font-size: inherit;
        color:black !important;
    }
</style>

<div class="pm-banner-content">
    <div class="row">
        <div class="col-md-12 d-flex">
            <div class="pm-banner-text pm-headline pera-content col-md-6">
                <span class="pm-title-tag">&nbsp;&nbsp;&nbsp;&nbsp;JNCH Visitor Pass</span>
                <br><br>
                <h2>JNCH Visitor</h2>
               
                <div class="row" style="margin-bottom: 20px;">
                    <div class="col-lg-3">
                        <div class="resultImage">
                            <img src="~/assets/img/myimg/valid.png" id="validimg" style="display:none" />
                            <img src="~/assets/img/myimg/invalid.png" id="invalidimg" style="display:none" />
                        </div>
                    </div>
                    <div class="col-lg-9" id="Details_after_Scan" style="display:none;">
                        <div class="row">
                            <label for="visitorName" class="Scanned_Lable">Visitor Name:</label>
                            <div class="col-md-6">
                                <input type="text" name="visitorName" id="visitorName" readonly class="form-control Scanned_Details" />
                            </div>
                        </div>

                        <div class="row">
                            <label for="visitorToken" class="Scanned_Lable">Visitor Token:</label>
                            <div class="col-md-6">
                                <input type="text" name="visitorToken" id="visitorToken" readonly class="form-control Scanned_Details" />
                            </div>
                        </div>

                        <div class="row">
                            <label for="visitorOfficer" class="Scanned_Lable">Visitor Officer:</label>
                            <div class="col-md-6">
                                <input type="text" name="visitorOfficer" id="visitorOfficer" readonly class="form-control Scanned_Details" />
                            </div>
                        </div>

                        <div class="row">
                            <label for="visitorDepartment" class="Scanned_Lable">Visitor Department:</label>
                            <div class="col-md-6">
                                <input type="text" name="visitorDepartment" id="visitorDepartment" readonly class="form-control Scanned_Details" />
                            </div>
                        </div>
                    </div>

                </div>
                @*<div class="d-flex">
                    <div class="ei-banner-btn">
                        <a href="@Url.Action("StepOne", "CheckIn")">
                            <span>Check-in</span>
                        </a>
                    </div>
                    <div class="ei-banner-btn ml-2">
                        <a href="@Url.Action("ScanQr", "CheckIn")">
                            <span>Scan QR</span>
                        </a>
                    </div>
                </div>*@
            </div>
            <div class="pm-banenr-vedio d-flex justify-content-end col-md-6 vedioPreview">
               
                <div class="modal-body">


                    <!-- QR SCANNER CODE BELOW  -->
                    <div class="col">
                        <div class="col">
                            <div id="reader"></div>
                        </div>
                        <div class="col" style="padding: 30px">
                            @*<h4>Scan Result </h4>*@
                            <div id="result">
                                Result goes here
                            </div>
                           
                        </div>

                    </div>
                </div>

            </div>


        </div>

    </div>

</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/html5-qrcode/2.2.0/html5-qrcode.min.js"></script>

<script>
    // When scan is successful, the function will process the data
function onScanSuccess(qrCodeMessage) {
    document.getElementById("result").innerHTML =
        '<span class="result">' + qrCodeMessage + "</span>";

    ValidateVisitor(qrCodeMessage);

    $("#ScanResult").val(qrCodeMessage);


}

// When scan is unsuccessful, the function will handle the error message
function onScanError(errorMessage) {
    // Handle Scan Error
}

// Setting up Qr Scanner properties
var html5QrCodeScanner = new Html5QrcodeScanner("reader", {
    fps: 10,
    qrbox: 250
});

// Initialize the QR code scanner
html5QrCodeScanner.render(onScanSuccess, onScanError);

</script>
<script>
function ValidateVisitor(qrCodeMessage) {
    $("#qrCodeMessage").val(qrCodeMessage);


    $.ajax({
        data: { Token: qrCodeMessage },
        type: "GET",
        contentType: "application/json; charset=utf-8",
        url: "/CheckIn/ValidateVisitor",
        success: function (result) {
    debugger
            if (result.Message == 'SUCCESS') {
                var token = result.TokenNo;       
                $("#validimg").show();
     $("#invalidimg").hide();
                AddVisitorCheckIn(qrCodeMessage); 
            } 
    else {
    debugger
                //alert("Invalid QR!");
               $("#invalidimg").show();
               $("#validimg").hide();
               $("#Details_after_Scan").hide();
                beep();
            }
        }

    });
}


 function ViewVisitorPassDetails(qrCodeMessage) {
    debugger
        $("#qrCodeMessage").val(qrCodeMessage);
    $("#Details_after_Scan").show();
     $("#result").hide();
    //alert(qrCodeMessage);
            $.ajax({
                url: "/CheckIn/ViewVisitorPassDetails",
                    data: '{token: ' + qrCodeMessage + '}',
                type: "POST",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    debugger;
                    $("#visitorName").val(data.FirstName);

                    $("#visitorToken").val(data.TokenNo);

                    $("#visitorOfficer").val(data.OfficerName);

                    $("#visitorDepartment").val(data.DepartmentName);

                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                  //  $("#tracker-loader").fadeOut("slow");
                }
            });

        }


    
      function hideAddPage() {
        $('#passDetails').show();
        $('#resultBox').hide();
    }


    function AddVisitorCheckIn(qrCodeMessage) {
    // Use a try-catch block to handle any potential errors
    try {
    debugger
        // Make an AJAX request
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: "/CheckIn/AddVisitorCheckIn",
            data: JSON.stringify({ Token: qrCodeMessage }), // Send data as JSON string
            success: function (message) {
    debugger
                // Check the result from the server
                if (message === 'SUCCESS') {
                    // If successful, show an alert and call another function
                    //alert('Check-in successful');
                    ViewVisitorPassDetails(qrCodeMessage);
                } else {
                    // If unsuccessful, show an alert
                    alert('Check-in unsuccessful');
                }
            },
            error: function () {
                // Handle AJAX error
                alert('Error during AJAX request');
            }
        });
    } catch (error) {
        // Handle any unexpected errors
        console.error('An error occurred:', error);
    }
}


    function beep() {
    var audio = new Audio('/assets/sound/mixkit-classic-alarm-995.wav'); // Replace with the path to your beep sound file
    audio.play();
}

</script>

MVC.Web/Views/CheckIn/ShowCheckIn.cshtml
@{
    ViewBag.Title = "Show";
    Layout = "~/Views/Shared/_FrontendLayout.cshtml";
}
@model List<MVC.Domain.Model.VisitorModel>

@*<link href="~/assets/css/PrintPage.css" rel="stylesheet" />*@

<div class="card border-0">
    <div class="card-body">
        <div class="card" style="border: 0;">
            <div class="card-body ">

                <div class="front" style="background-color: #ffffff; display: flex; flex-direction: row; justify-content: center; width: 100%;" id="printablediv">
                    <div class="div" style="background-color: #ffffff; width: 214px; height: 322px; position: relative; border: 1px solid grey">
                        <img style="height: 54px; top: 268px; position: absolute; width: 214px; left: 0;" class="shape" src="~/assets/img/shape-2.png" />
                        <div class="overlap-group" style="position: absolute; width: 214px; height: 173px; top: 0; left: 0;">
                            <img class="img" src="~/assets/img/shape-1.png" style="height: 147px; top: 0; position: absolute; width: 212px; left: 0;"/>
                            @*<img class="img-2" src="~/assets/img/img02-6.svg" />*@
                            <img class="img-2" src="~/Images/Visitor_liveImage/@ViewBag.VisitorPic" style="position: absolute; width: 69px; height: 69px; top: 104px; left: 70px; border-radius: 50%" />
                            <div class="comjpany-name-logo" style="position: absolute; width: 198px; height: 20px; top: 67px; left: 5px;">
                                <div class="group" style="position: relative; width: 200px; height: 20px;"><div class="name" style="width: 198px; color: #2d2121; font-size: 12px; position: absolute; top: 0; left: 0; font-family: 'Kameron', Helvetica; font-weight: 700; letter-spacing: 0; line-height: normal;">Jawaharlal Nehru Custom House</div></div>
                            </div>
                            <img class="image" src="~/assets/img/image-2.png" style="position: absolute; width: 54px; height: 61px; top: 5px; left: 75px; object-fit: cover;" />
                            <div class="text-wrapper" style="position: absolute; width: 101px; top: 82px; left: 59px; font-family: 'Kameron', Helvetica; font-weight: 700; color: #151e6b; font-size: 13px; letter-spacing: 0; line-height: normal;">VISITING PASS</div>
                        </div>
                        <p class="satf-descro-topm" style="position: absolute; width: 126px; top: 211px; left: 12px; font-family: 'Roboto', Helvetica; font-weight: 400; color: transparent; font-size: 8px; letter-spacing: 0; line-height: normal;">
                            <span class="span" style="font-weight: 700; color: #2e9da6;">Officer</span>
                            <span class="text-wrapper-2" style="color: #2e9da6;">&nbsp;&nbsp; </span>
                            <span class="text-wrapper-3" style="color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            <span class="text-wrapper-4" style="font-weight: 500; color: #000000;"> : @ViewBag.Officer<br /></span>

                            <span class="span" style="font-weight: 700; color: #2e9da6;">Phone</span>
                            <span class="text-wrapper-3"  style="color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
                            <span class="text-wrapper-4" style="font-weight: 500; color: #000000;">:@ViewBag.Phone<br /></span>
                            <span class="span">E-mail</span>
                            <span class="text-wrapper-3"  style="color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
                            <span class="text-wrapper-4" style="font-weight: 500; color: #000000;">: @ViewBag.Email</span>
                        </p>
                        <div class="staff-name" style="position: absolute; width: 114px; height: 18px; top: 177px; left: 56px;"><div class="name-2" style="width: 112px; color: #030708; font-size: 16px; white-space: nowrap; position: absolute; top: 0; left: 0; font-family: 'Kameron', Helvetica; font-weight: 700; letter-spacing: 0; line-height: normal;">@ViewBag.VisitorName</div></div>
                        @*<img class="image-2" src="~/assets/img/image-1.png" />*@
                        <img class="image-2" src="@ViewBag.Path" style="position: absolute; width: 64px; height: 59px; top: 203px; left: 140px;">

                    </div>
                </div>

                <div class="row justify-content-md-center" style="padding-bottom:30px">
                    <div class="col-md-3">
                        <div style="margin-top: 10px;" class="justify-content-center">
                            <div class="btn-group btn-group-justified">
                                <a href=@Url.Action("Visitor", "Visitor") class="btn btn-primary text-white">
                                    <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
                                </a>
                                <a href="#" id="print" class="btn btn-success text-white" onclick="printDiv()">
                                    <i class="fa fa-print" aria-hidden="true"></i> Print
                                </a>
                                <a href=@Url.Action("Index", "Home") class="btn btn-danger text-white ">
                                    <i class="fa fa-home" aria-hidden="true"></i> Home
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>



@*<script>
    function printDiv() {
    debugger;
    var printWindow = window.open('', '_blank');
    printWindow.document.write('<html><head><title>Print</title>');

    printWindow.document.write('</head><body>');
    printWindow.document.write(document.getElementById('printablediv').innerHTML);
    printWindow.document.write('</body></html>');
    printWindow.document.close();

    printWindow.onload = function () {
        printWindow.print();
        printWindow.onafterprint = function () {
            printWindow.close();
        };
    };
}


</script>*@

<script>
    function printDiv() {
    debugger;
    var printWindow = window.open('', '_blank');
    printWindow.document.write('<html><head><title>Print</title>');
    // Add styles for centering and adjusting height
    printWindow.document.write('<style>body { display: flex; align-items: center; justify-content: center; height: 50vh; }</style>');
    printWindow.document.write('</head><body>');
    printWindow.document.write(document.getElementById('printablediv').innerHTML);
    printWindow.document.write('</body></html>');
    printWindow.document.close();

    printWindow.onload = function () {
        printWindow.print();
        printWindow.onafterprint = function () {
            printWindow.close();
        };
    };
}

</script>

MVC.Web/Views/CheckIn/StepTwo.cshtml
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_FrontendLayout.cshtml";
}
<link href="~/assets/css/id-card-print.css" rel="stylesheet" />
<div class="container camera-container">
    <div class="card border-0 bg-body">
     
        <form action=@Url.Action("ShowCheckIn", "CheckIn") method="POST" enctype="multipart/form-data" >
            <input type="hidden" name="_token" value="Q7hXgdIgg3KrSSnijAsnernaMgiVma8VFPXRIcLw">
            <div class="card-body custom-camera">
                <div class="row">
                    <div class="col-md-6 left-div">
                        <div class="card border-0 ">
                            <h4 style="color: #111570;font-weight: bold" class="text-center">Take Visitor Photo</h4>

                            <div class="card-body">
                                <div class="video-options mb-4">
                                    <select name="" id="" class="custom-select">
                                        <option value="">Select camera</option>
                                    </select>
                                </div>
                                <div class="row">
                                    <div class="col-9">
                                        <video width="100%" height="200px" id="videos" autoplay></video>
                                        <canvas class="d-none" style="border:5px solid #d3d3d3; display: none"></canvas>
                                        <input type="hidden" id="image" name="photo" value="">
                                    </div>
                                    <div class="col-3">
                                        <button type="button" id="screenshot" title="ScreenShot" class='retakephoto'>
                                            <img class="img" src="https://demo.quickpass.xyz/images/capture.png" style="height: 80px">
                                        </button>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <span class="text-center"></span>
                    </div>

                    <div class="col-md-6 ">
                        <div class="img-cards" id="printidcard">
                            <div class="id-card-holder">
                                <div class="id-card custom-id-card">
                                    <div class="id-card-photo">
                                        <img id="card-img" style="width: 120px;height: 120px;" class="screenshot-image" alt="">

                                    </div>
                                    <h2 class="name mt-4">sdfsff dsffd</h2>
                                    <h2 class="info"> Phone : 785757533365</h2>
                                    <h2 class="info">Email : admin@example.com</h2>

                                    <h2 class="visit mt-4">VISITED TO</h2>
                                    <h3 class="email">Officer: Ramdas Kale</h3>
                                    <hr class="bar">
                                    <p class="company">Visitor Pass </p>
                                    <p class="company">Mumbai, India. </p>
                                    <p class="email">E-mail :info@inilabs.xyz </p>
                                </div>
                            </div>

                        </div>

                    </div>


                </div>

            </div>
            <div class="card-footer custom-footer">
                <div class="row">
                    <div class="col-md-6">
                        <a href="@Url.Action("StepOne", "CheckIn")" class="btn btn-primary float-left text-white cancel px-5 py-2">
                            Back
                        </a>
                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="btn  float-right continue text-light px-5 py-2 btn-submit-two" id="hide" onclick="SaveAndContinue()">
                            Continue
                        </button>
                    </div>
                </div>
            </div>

        </form>




    </div>
    
</div>